upgrade: Avoid CR update if there is nothing change
longhorn/longhorn-manager pull request #1058
Opened 2021-09-21 12:23 UTC by shuo-wu

This is a surgery fix for the original issue, which can not avoid
the old upgrade path intervening longhorn manager pod start.

To resolve this issue, Longhorn needs to somehow understand the
old version and the current version during system upgrade.

Longhorn/longhorn#2582

2021-09-21 12:25 UTC, shuo-wu commented
Since it's hard to reproduce the bug, I am not sure if we can find a way to test this fix.

2021-09-22 05:45 UTC, innobead approved these changes

2021-09-22 05:52 UTC, innobead requested changes

2021-09-22 05:52 UTC, innobead commented on upgrade/v102to110/upgrade.go
>  			if _, err := lhClient.LonghornV1beta1().Volumes(namespace).UpdateStatus(context.TODO(), &v, metav1.UpdateOptions{}); err != nil {
When `requireUpdate` is true, you only update the volume status but actually, but how about the change of `v.spec.accessmode` which will not be taken effect if only updating the status.

2021-09-22 05:54 UTC, innobead commented
I am also curious a bit about this change which corner cases will this PR actually fix?

2021-09-22 08:52 UTC, innobead commented
> I am also curious a bit about this change which corner cases will this PR actually fix?

This is from @shuo-wu 
> The issue mentioned in the ticket are caused by this blind volume update conflict.
> E.g., when users upgrade the Longhorn from v1.1.0 to v1.1.x or v1.2.0, this volume update in the old upgrade path should not do anything But actually NO. Since this is neither deep equal check nor some flags like requireUpdate that indicate the update skip.

2021-09-22 09:24 UTC, innobead approved these changes

2021-09-22 09:24 UTC, merged

2021-09-22 09:24 UTC, innobead commented
@shuo-wu please backport to 1.2.x.