remove unwanted variable
longhorn/longhorn-manager pull request #1092
Opened 2021-10-13 21:42 UTC by slayer321

Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
related to bugbash

https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22Staticcheck%22%7CSA4006

2021-10-15 10:09 UTC, shuo-wu commented on controller/kubernetes_node_controller.go
> +
Besides, I realized that Longhorn updates node CRs blindly and immediately in this controller. We will open a separate PR for this issue.

2021-10-18 02:26 UTC, shuo-wu commented on datastore/longhorn.go
> +	nodeSelector, _ := getNodeSelector(name)
Thank you for the correction. The code you present is what I preferred.

As long as there is an error, the function should not continue, and callers won't use the pointer of the slice.

2021-10-20 04:09 UTC, shuo-wu requested changes

2021-10-20 04:09 UTC, shuo-wu commented on controller/controller_test.go
> +	b.Requests[corev1.ResourceCPU], _ = resource.ParseQuantity("250m")
Use `c.Assert(err, IsNil)` rather than ignoring it in the unit tests. Similar below.

2021-10-20 04:09 UTC, shuo-wu commented on controller/instance_manager_controller_test.go
> +		_, _ = kubeClient.CoreV1().Nodes().Create(context.TODO(), kubeNode2, metav1.CreateOptions{})
Use `c.Assert(err, IsNil)` rather than ignoring it.

2021-11-19 07:26 UTC, jenting commented
@slayer321 are you willing to address this https://github.com/longhorn/longhorn-manager/pull/1092#discussion_r732400289?

2021-11-20 08:05 UTC, slayer321 commented
yes, I have already done that. You can check my last commit

2021-11-22 01:16 UTC, jenting commented
> b.Requests[corev1.ResourceCPU]

But I still see the error did not check https://github.com/longhorn/longhorn-manager/blob/23234846129c26afedecd2fd45654af779286928/controller/controller_test.go#L312-L314

2021-11-22 03:32 UTC, shuo-wu commented on controller/kubernetes_node_controller.go
> +
The fix for this part is in PR https://github.com/longhorn/longhorn-manager/pull/1148

2021-11-22 03:41 UTC, shuo-wu commented on controller/controller_test.go
> +	b.Requests[corev1.ResourceCPU], _ = resource.ParseQuantity("250m")
```suggestion
	b.Requests[corev1.ResourceCPU], err = resource.ParseQuantity("250m")
	c.Assert(err, IsNil)
```

Similar below

2022-01-18 06:23 UTC, innobead commented
Closing for long inactivity. @slayer321 feel free to continue this PR later on. Thank you.

2022-01-18 06:23 UTC, closed without merging