Fix staticcheck issues
longhorn/longhorn-manager pull request #1101
Opened 2021-10-14 08:49 UTC by Shatakshi0805

Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>
Related to Bugbash.

2021-10-15 12:49 UTC, shuo-wu requested changes

2021-10-15 12:49 UTC, shuo-wu commented on controller/share_manager_controller.go
> +	return !(!hasActiveWorkload)
```suggestion
	return hasActiveWorkload
```

2021-11-19 07:23 UTC, jenting commented
@Shatakshi0805 are you willing to keep working on this PR?

2021-12-29 12:32 UTC, Shatakshi0805 commented
apologies for being inactive here. i have been quite caught up due to college work and exams. i will update the pr with requested changes as soon as possible.

2021-12-30 02:59 UTC, shuo-wu commented
> apologies for being inactive here. i have been quite caught up due to college work and exams. i will update the pr with requested changes as soon as possible.

Sure. Thank you! Feel free to ping us after updating this PR

2022-06-24 07:42 UTC, closed without merging