grpc-proxy: fix ctx cancelled during replica list
longhorn/longhorn-manager pull request #1349
Opened 2022-05-27 09:59 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/3546

2022-05-28 00:11 UTC, PhanLe1010 commented
Could you explain a bit more about the issue that we are solving?

2022-05-29 14:18 UTC, innobead commented
I think @c3y1huang is trying to fix a concurrent issue that `engineClientProxy` is closed during using it to wait for the replica to be added.

@c3y1huang What do you think the below fix instead?

```golang
	engineClientProxy, err := ec.getEngineClientProxy(e, e.Status.CurrentImage)
	if err != nil {
		return err
	}
        engineClientProxy.Close()
``
, then just create another engine client in the goruntine.

2022-05-29 14:19 UTC, innobead requested changes
I think @c3y1huang is trying to fix a concurrent issue that `engineClientProxy` is closed during using it to wait for the replica to be added.

@c3y1huang I think we can remove `engineClientProxy.Close()` and just leave the variable to garbage collected by the go runtime instead of the graceful shutdown, so you don't need to change any other code, but need to check if this will cause the connection to leak? or the other way is to have another engine client proxy in the goroutine instead.

2022-05-30 01:49 UTC, innobead commented on controller/engine_controller.go
> +		engineClientProxyGo, err := ec.getEngineClientProxy(e, e.Status.CurrentImage)
nit: `engineClientProxy` should be able to be shadowed in another scope, so basically you can use the same name as outer if you want.

2022-05-30 02:01 UTC, innobead approved these changes

2022-05-30 02:01 UTC, merged