Handle Kubernetes node event and cond.
longhorn/longhorn-manager pull request #1549
Opened 2022-11-15 14:21 UTC by mantissahz

Move checking the manager pod status after checking Kubernetes node status and not check the manager pod status if Kubernetes node status is not ready.

longhorn/longhorn#1449

2022-11-16 10:36 UTC, innobead requested changes

2022-11-16 10:36 UTC, innobead commented on controller/node_controller.go
> +		podConditions := pod.Status.Conditions
Can you format this way?

```go
if pod.Spec.NodeName != node.Name {
    continue
}

nodeManagerFound = true
if !kubeNodeIsReady {
    break
}

podConditions := pod.Status.Conditions
...
```

2022-11-16 10:36 UTC, innobead commented on controller/node_controller.go
> +		}
Don't think you need this, but rather let the below logic to update the node condition.

2022-11-16 10:36 UTC, innobead commented on controller/node_controller.go
> +			}
Why not?

```go
if podCondition.Status == v1.ConditionTrue && pod.Status.Phase == v1.PodRunning {
    // create the event after `UpdateNodeStatus` without the error `IsConflict`
    if types.GetCondition(node.Status.Conditions, longhorn.NodeConditionTypeReady).Status != longhorn.ConditionStatusTrue {
        nodeIsReadyEventMsg = fmt.Sprintf("Node %v is ready", node.Name)
        nodeIsReadyEventType = v1.EventTypeNormal
        node.Status.Conditions = types.SetCondition(node.Status.Conditions, longhorn.NodeConditionTypeReady, longhorn.ConditionStatusTrue, "", nodeIsReadyEventMsg)    
    }
} else {
    // create the event after `UpdateNodeStatus` without the error `IsConflict`
    if types.GetCondition(node.Status.Conditions, longhorn.NodeConditionTypeReady).Status != longhorn.ConditionStatusFalse {
        nodeIsReadyEventMsg = fmt.Sprintf("Node %v is down: the manager pod %v is not running", node.Name, pod.Name)
        nodeIsReadyEventType = v1.EventTypeWarning
        node.Status.Conditions = types.SetCondition(node.Status.Conditions, longhorn.NodeConditionTypeReady, longhorn.ConditionStatusFalse, string(longhorn.NodeConditionReasonManagerPodDown), nodeIsReadyEventMsg)
    }
}
```

2022-11-16 14:10 UTC, mantissahz commented on controller/node_controller.go
> +		podConditions := pod.Status.Conditions
Modified.

2022-11-16 14:10 UTC, mantissahz commented on controller/node_controller.go
> +	nodeManagerFound := false
Modified.

2022-11-18 05:41 UTC, innobead commented
ref: https://github.com/longhorn/longhorn/issues/1449#issuecomment-1319574678

2022-11-18 05:45 UTC, mantissahz commented
According to https://github.com/longhorn/longhorn/issues/1449#issuecomment-1319574678
Close this PR.

2022-11-18 05:45 UTC, closed without merging