feat(support-bundle): Add new parameter: `SPECIFY_COLLECTOR_SCRIPT` to execute specified support-bundle-kit collector
longhorn/longhorn-manager pull request #1754
Opened 2023-03-07 10:41 UTC by weizhe0422

[Longhorn 5073](https://github.com/longhorn/longhorn/issues/5073)

Signed-off-by: Ray Chang <ray.chang@suse.com>

A New parameter: `SPECIFY_COLLECTOR_SCRIPT` is passed to support-bundle-kit to execute the specified collector script.  And the [support-bundle-kit PR](https://github.com/rancher/support-bundle-kit/pull/63) will also accept this new parameter and execute `collector-longhorn.sh` to collect system information and logs.

2023-03-07 13:38 UTC, innobead requested changes

2023-03-07 13:38 UTC, innobead commented on controller/support_bundle_controller.go
> +									Name:  "SPECIFY_COLLECTOR_SCRIPT",
Suggest having the same pattern like `SUPPORT_BUNDEL_COLLECTOR` instead.

2023-03-07 15:32 UTC, merged

2023-03-08 05:25 UTC, weizhe0422 commented
@Mergifyio backport v1.4.x v1.3.x

2023-03-08 05:35 UTC, weizhe0422 commented
The backport to v1.3.x [PR#1756 https://github.com/longhorn/longhorn-manager/pull/1756] was closed since the support bundle kit has only been introduced since v1.4.x.

2023-03-08 06:55 UTC, innobead commented
@weizhe0422 this is no `backport/v1.3.x` for this issue. Please just follow the backport labels on that issue to do the backport instead.