style: reformat backing image controller log message
longhorn/longhorn-manager pull request #1804
Opened 2023-03-23 07:07 UTC by ChanYiLin

Ref: longhorn/longhorn 5015

- `Info` logs should start with uppercase V+ed or V+ing
- `Warn/Error` logs should start with lowercase V+ed or V+ing
- change `Debug` logs to `Info`, `Warn` or remove them

2023-03-23 07:08 UTC, ChanYiLin commented
@innobead we can use this PR as example and make sure we are on the same page of logging reformat, thanks!

2023-03-23 07:15 UTC, derekbit commented on controller/backing_image_controller.go
> +		logrus.WithError(err).Warnf("error syncing Longhorn backing image %v", key)
IIRC, @innobead  we use uppercase for the log message, right?

2023-03-23 07:20 UTC, derekbit commented
IIRC, @innobead  we use uppercase for the log message regardless of the level as a convention, right?

```
logrus.WithError(err).Error("Error....")
```

```
return fmt.Errorf("error ...")
```

2023-03-23 07:20 UTC, derekbit commented
IIRC, @innobead  we use uppercase for the log message regardless of the level as a convention, right?

```
logrus.WithError(err).Error("Error....")
```

```
return fmt.Errorf("error ...")
```

2023-03-23 07:21 UTC, derekbit commented on controller/backing_image_controller.go
> +		logrus.WithError(err).Warnf("error syncing Longhorn backing image %v", key)
Violate the existing convention. Please check https://github.com/longhorn/longhorn-manager/pull/1804#issuecomment-1480707966

2023-03-23 07:21 UTC, derekbit commented on controller/backing_image_controller.go
> +	logrus.WithError(err).Warnf("dropping Longhorn backing image %v out of the queue", key)
See 1.

2023-03-23 07:21 UTC, derekbit commented on controller/backing_image_controller.go
> +			bic.logger.WithField("backingImage", name).WithError(err).Error("failed to retrieve backing image from datastore")
See 1.

2023-03-23 07:21 UTC, derekbit commented on controller/backing_image_controller.go
> +			log.Warn("waiting for all replicas stopping using this backing image before removing the finalizer")
See 1.

2023-03-23 07:57 UTC, ChanYiLin commented
> ~IIRC, @innobead we use uppercase for the log message regardless of the level as a convention, right?~
> 
> We use uppercase for the log message regardless of the level as a convention. [longhorn/longhorn#5015 (comment)](https://github.com/longhorn/longhorn/issues/5015#issue-1481250309)
> 
> ```
> logrus.WithError(err).Error("Error....")
> ```
> 
> ```
> return fmt.Errorf("error ...")
> ```

Oh I misunderstood the description in [#5015](https://github.com/longhorn/longhorn/issues/5015)
For logging no matter what level, start with uppercase.
Error message means message inside `error` not logging, and it should start with lowercase

2023-04-06 07:18 UTC, innobead requested changes
In general, LGTM. Just one log level needs to change. Thanks!

2023-04-06 07:18 UTC, innobead commented on controller/backing_image_data_source_controller.go
> +			log.WithError(err).Infof("Need to wait for volume attachment before handling key %v", key)
Change to warnf instead.

2023-04-07 07:45 UTC, ChanYiLin commented on controller/backing_image_data_source_controller.go
> +			log.WithError(err).Infof("Need to wait for volume attachment before handling key %v", key)
fixed, thanks!

2023-04-07 07:46 UTC, innobead approved these changes

2023-04-07 07:57 UTC, merged

2023-04-07 08:45 UTC, innobead commented
@Mergifyio backport v1.4.x