Update logs for volume spec size change
longhorn/longhorn-manager pull request #1814
Opened 2023-03-29 02:31 UTC by shuo-wu

Longhorn/longhorn#5513

2023-03-29 02:35 UTC, derekbit submitted a review, later dismissed

2023-03-30 07:47 UTC, innobead requested changes

2023-03-30 07:47 UTC, innobead commented on manager/volume.go
> +	logrus.Infof("Expanding volume %v from %v to %v requested", v.Name, v.Spec.Size, size)
`v.Spec.Size` is the same as `size`. You should log with the original volume size instead.

2023-03-30 08:51 UTC, merged

2023-03-30 09:03 UTC, innobead commented
@Mergifyio backport v1.4.x