feat(recurring-job): set recurring job to pvc
longhorn/longhorn-manager pull request #1911
Opened 2023-05-19 00:32 UTC by c3y1huang

https://github.com/longhorn/longhorn/discussions/5773

2023-05-19 12:02 UTC, c3y1huang commented
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3860/

2023-05-22 00:51 UTC, c3y1huang commented
[Test PVC recurring job sync from Volume after upgrade](https://github.com/longhorn/longhorn-tests/blob/2d0aa0d45e0c2ea3810f2f3e95e5df0d65361f03/docs/content/manual/release-specific/v1.5.0/test-pvc-recurring-job-sync-after-upgrade.md): PASS

2023-05-22 11:04 UTC, innobead reviewed
Can we make the implementation simpler as below w/ fewer resources (w/o a new PVC controller), WDYT?

1. in volume_controller, when resync, check if the volume has PVC and it has recurring jobs labels
2. If yes, override the volume labels, because PVC labels have higher priority.
3. If no PVC, all things are the same as usual

Just need to define the priority for which resource will decide the labels, no need to do sync efforts which will require another PVC controller in the implementation and seem not really necessary cost. Still, we can achieve the case for gitops use case.

2023-05-24 06:22 UTC, c3y1huang commented
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3883/

2023-05-25 15:19 UTC, innobead commented on datastore/longhorn.go
> +func (s *DataStore) DeleteRecurringJobLabelOn(volume *longhorn.Volume, labelKey string) (*longhorn.Volume, error) {
`DeleteRecurringJobLabelFromVolume`

2023-05-25 15:26 UTC, innobead commented on types/types.go
> +func GetRecurringJobLabelKeyBy(name string, isGroup bool) string {
`GetRecurringJobLabelKeyByType`

2023-05-25 15:28 UTC, innobead commented on controller/recurring_job_controller.go
> +func syncRecurringJobLabelsTo(targetKind string, targetObj, sourceObj runtime.Object, log logrus.FieldLogger) error {
`syncRecurringJobLabelsFromSourceResource`

2023-05-25 15:30 UTC, innobead commented on controller/volume_controller.go
> +	if kubeStatus.PVCName == "" {
Do we need to check if the PVC still bound to the volume via `LastPVCRefAt`?

2023-05-25 15:31 UTC, innobead commented on types/types.go
> +func IsRecurringJobLabel(key string) bool {
Add doc.

2023-05-25 15:40 UTC, innobead commented on manager/volume.go
> +	return m.ds.UpdateVolume(volume)
Why not just updating the volume in datastore's `DeleteRecurringJobLabelOn`?

2023-05-25 15:43 UTC, innobead commented on controller/recurring_job_controller.go
> +				groups[group] = false
break?

2023-05-26 09:41 UTC, c3y1huang commented
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3911/

2023-05-29 04:57 UTC, innobead requested changes
Some comments need to resolve.

I forgot why we couldn't remove a group label from a volume if the group is being used. What does that matter?

2023-05-29 04:57 UTC, innobead commented on controller/recurring_job_controller.go
> +		err = errors.Wrap(err, "failed to cleanup recurring job labels from Volumes and PVCs")
`"failed to cleanup recurring job labels %v from Volumes and PVCs"`

2023-05-29 04:57 UTC, innobead commented on controller/recurring_job_controller.go
> +		return errors.Wrap(err, "failed to sync recurring job labels to PVC")
`"failed to sync recurring job labels to PVC %v"`

2023-05-29 04:57 UTC, innobead commented on controller/volume_controller.go
> +		return errors.Wrap(err, "failed attempting to sync PVC recurring job labels")
`failed attempting to sync PVC recurring job labels from volume %v`

2023-05-29 04:57 UTC, innobead commented on controller/recurring_job_controller.go
> +func (c *RecurringJobController) updatePVCRecurringJobLabelsFrom(volume *longhorn.Volume) (err error) {
Rename `updatePVCRecurringJobLabelsFromVolume`

2023-05-29 05:04 UTC, c3y1huang commented
> I forgot why we couldn't remove a group label from a volume if the group is being used. What does that matter?

When a RecurringJob CR gets deleted, we also cleans the labels in the Volumes label. So we need to ensure the group label has no-op (no recurring jobs).

2023-05-29 05:14 UTC, innobead commented
> > I forgot why we couldn't remove a group label from a volume if the group is being used. What does that matter?
> 
> When a RecurringJob CR gets deleted, we also cleans the labels in the Volumes label. So we need to ensure the group label has no-op (no recurring jobs).

I see, so it's about removing the unused group label from other volumes.

2023-05-29 05:22 UTC, innobead approved these changes

2023-05-29 05:29 UTC, merged