fix(logging): review and adjust log message and level in kubernetes resouce and setting controllers
longhorn/longhorn-manager pull request #1938
Opened 2023-06-01 07:44 UTC by ChanYiLin

ref: [longhorn/longhorn 5888](https://github.com/longhorn/longhorn/issues/5888)

2023-06-01 10:04 UTC, innobead requested changes
In general, LGTM. Some comments need to resolve. For some improvment items, please create issues for following tracking.

2023-06-01 10:04 UTC, innobead commented on controller/kubernetes_secret_controller.go
> +	ks.logger.Debug("Triggering sync backup target because the credential secret change")
Can be info?

2023-06-02 03:06 UTC, ChanYiLin commented on controller/kubernetes_configmap_controller.go
> +		kc.logger.WithError(err).Warnf("Failed to syncing ConfigMap %v", key)
Got it.
Also as discussed, this should also be `Error` since it failed to sync this obj and the error is not handled in this reconcile loop.

2023-06-02 03:16 UTC, ChanYiLin commented on controller/kubernetes_pv_controller.go
> +		return false, errors.Wrap(err, "failed to get volume for cleanup in cleanupForPVDeletion")
We already have an issue for this
https://github.com/longhorn/longhorn/issues/5509

2023-06-02 03:25 UTC, ChanYiLin commented on controller/kubernetes_pv_controller.go
> +		err = errors.Wrapf(err, "failed to sync PV %v", key)
We already have an issue for this
https://github.com/longhorn/longhorn/issues/5509

2023-06-02 03:25 UTC, ChanYiLin commented on controller/kubernetes_node_controller.go
> +			logrus.Warnf("Failed to set default node tags for node %v: %v", node.Name, err)
We already have an issue for this
https://github.com/longhorn/longhorn/issues/5509

2023-06-02 03:30 UTC, ChanYiLin commented
Hi @innobead , fixed, thanks!

2023-06-02 06:07 UTC, innobead approved these changes

2023-06-02 06:19 UTC, merged