fix(logging): review and adjust log message and level in other controllers
longhorn/longhorn-manager pull request #1946
Opened 2023-06-02 06:35 UTC by ChanYiLin

ref: [longhorn/longhorn#5888](https://github.com/longhorn/longhorn/issues/5888)

2023-06-07 10:51 UTC, innobead requested changes
In general, LGTM. Some comments need to resolve.

2023-06-07 10:51 UTC, innobead commented on controller/volume_controller.go
> +		log.Warnf("unexpected state for migration, current engine count %v has invalid migration engine %v",
`Unexpected ..`

2023-06-08 06:26 UTC, ChanYiLin commented on controller/share_manager_controller.go
> +		getLoggerForVolume(c.logger, volume).Info("Enqueuing share manager for volume")
removed, thanks!

2023-06-08 06:27 UTC, ChanYiLin commented on controller/share_manager_controller.go
> +	c.logger.WithField("pod", pod.Name).WithField("shareManager", smName).Info("Enqueuing share manager for pod")
removed

2023-06-08 06:28 UTC, ChanYiLin commented on controller/share_manager_controller.go
> +		c.logger.Warn("Unsetting endpoint due to missing service for share-manager")
Fixed,

2023-06-08 06:28 UTC, ChanYiLin commented on controller/share_manager_controller.go
> +				getLoggerForShareManager(c.logger, sm).Infof("Stopping share manager because the volume %v is not found", sm.Name)
Fixed

2023-06-08 06:32 UTC, ChanYiLin commented on controller/volume_controller.go
>  	}
Fixed.

2023-06-08 06:33 UTC, ChanYiLin commented on controller/volume_controller.go
> +		log.Warnf("unexpected state for migration, current engine count %v has invalid migration engine %v",
Fixed

2023-06-10 07:52 UTC, innobead approved these changes
LGTM.

@ChanYiLin although we merged all changes here, need to continue following up on changed logging, or see if anything is missed to change. Also, community feedback matters, so ensure our logging convention does make sense. Change the convention if needed later. 

BTW, need to create or leverage a validation way later to reduce tedious manual review.

2023-06-10 07:52 UTC, merged

2023-06-10 07:52 UTC, innobead commented
@mergify backport v1.5.x