feat(metrics): add pvc namespace to volume metrics
longhorn/longhorn-manager pull request #2284
Opened 2023-11-11 05:36 UTC by antoninferrand

https://github.com/longhorn/longhorn/issues/7077

2023-11-12 10:30 UTC, innobead submitted a review, later dismissed
LGTM

2023-11-12 10:31 UTC, innobead commented
@c3y1huang Please help review this.

2023-11-13 00:15 UTC, innobead commented
@mantissahz please help review this since Chinya is off today. Thanks.

2023-11-13 04:07 UTC, mantissahz approved these changes
LGTM and Verified.

@antoninferrand just one question.

I got the `namespace` label assigned with `longhorn-system` in default, and after you added this label, the label name would be `exported_namesapce` assigned with `default` if pvc was created in the namespace `default`.
Is this scenario what you expected?

2023-11-13 06:41 UTC, mantissahz commented
@Mergifyio backport v1.4.x,v1.5.x

2023-11-13 06:43 UTC, innobead requested changes

2023-11-13 06:43 UTC, innobead commented on metrics_collector/types.go
> +	namespaceLabel       = "pvc_namespace"
rename `pvcNamespaceLabel`

2023-11-13 06:48 UTC, mantissahz commented
>Maybe something like pvc_namespace ? WDYT ?

@antoninferrand That would be great.
I'd changed the label name, could you review it?

2023-11-13 06:49 UTC, mantissahz commented on metrics_collector/types.go
> +	namespaceLabel       = "pvc_namespace"
Modified. Thanks.

2023-11-13 06:52 UTC, innobead approved these changes

2023-11-13 06:57 UTC, merged

2023-11-13 06:58 UTC, mantissahz commented
@Mergifyio backport v1.4.x,v1.5.x

2023-11-13 06:59 UTC, mantissahz commented
@Mergifyio backport v1.4.x, v1.5.x