Reject the creation of encrypted v2 volume in validating webhook
longhorn/longhorn-manager pull request #2393
Opened 2023-12-21 03:11 UTC by derekbit

Longhorn/longhorn#7404

2023-12-21 12:22 UTC, innobead approved these changes

2023-12-21 12:23 UTC, innobead requested changes
Actually there is a missing change causing the PR check failed.

2023-12-22 03:06 UTC, derekbit commented
> Actually there is a missing change causing the PR check failed.

Fixed. The error is due to the API in unmerged PRs.

2023-12-22 04:26 UTC, innobead approved these changes

2023-12-22 04:26 UTC, merged