feat(metrics): support backing image metrics
longhorn/longhorn-manager pull request #2543
Opened 2024-01-30 08:22 UTC by ChanYiLin

ref: https://github.com/longhorn/longhorn/issues/7563

#### What this PR does / why we need it:
Support collect `BackingImage`, `BackupBackingImage` metrics

2024-01-31 09:01 UTC, c3y1huang requested changes

2024-02-21 09:23 UTC, ChanYiLin commented on metrics_collector/backing_image_collector.go
> +		return nil, errors.Wrapf(err, "failed to get node list")
Fixed, thanks!

2024-02-21 09:24 UTC, ChanYiLin commented on metrics_collector/backing_image_collector.go
> +					bc.logger.Warn("Failed to find nodeID with the given diskID %v of the BackingImage %v", diskID, backingImage.Name)
Fixed, thanks!

2024-03-26 15:13 UTC, innobead submitted a review, later dismissed
LGTM. 

Leave to Chinya final review before merging.

2024-04-17 02:14 UTC, c3y1huang requested changes

2024-04-17 02:14 UTC, c3y1huang commented on metrics_collector/metrics_collector.go
> +		logger.WithField("collector", subsystemBackingImage).WithError(err).Warn("Failed to register collector")
```suggestion
		logger.WithField("collector", subsystemBackupBackingImage).WithError(err).Warn("Failed to register collector")
```

2024-04-22 09:16 UTC, ChanYiLin commented on metrics_collector/metrics_collector.go
> +		logger.WithField("collector", subsystemBackingImage).WithError(err).Warn("Failed to register collector")
Fixed, thanks

2024-04-23 00:36 UTC, c3y1huang approved these changes

2024-04-23 01:05 UTC, merged