refactor: remove isCLIAPIVersionOne related codes
longhorn/longhorn-manager pull request #3060
Opened 2024-08-11 07:55 UTC by derekbit

#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#7191

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-08-11 09:19 UTC, innobead submitted a review, later dismissed

2024-08-11 09:21 UTC, innobead commented
The PR check failed due to a lint issue. Let's fix it before merging.

2024-08-11 13:12 UTC, derekbit commented
> The PR check failed due to a lint issue. Let's fix it before merging.

Fixed. Thank you.

2024-08-11 13:34 UTC, innobead requested changes

2024-08-11 13:34 UTC, innobead commented on controller/engine_controller.go
>  	// For incompatible engine, skip starting engine monitor and clean up fields when the engine is not running
Remove this outdated message.

2024-08-15 06:22 UTC, derekbit commented on controller/engine_controller.go
>  	// For incompatible engine, skip starting engine monitor and clean up fields when the engine is not running
Removed. Thank you.

2024-08-16 19:39 UTC, shuo-wu approved these changes

2024-08-16 19:43 UTC, PhanLe1010 commented on controller/instance_manager_controller.go
> +	if len(im.Status.Instances) > 0 { // nolint: staticcheck
Any idea why we need to have `nolint` here?

2024-08-16 19:43 UTC, PhanLe1010 approved these changes

2024-08-16 19:46 UTC, PhanLe1010 commented on controller/instance_manager_controller.go
> +	if len(im.Status.Instances) > 0 { // nolint: staticcheck
Oh. ok they are deprecated fields as @james-munson pointed out here https://github.com/longhorn/longhorn-manager/pull/3069

2024-08-18 12:17 UTC, innobead approved these changes

2024-08-18 12:17 UTC, merged