fix(uninstall): deleting failed backups when uninstalling
longhorn/longhorn-manager pull request #3427
Opened 2024-12-31 13:09 UTC by mantissahz

#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#10104

#### What this PR does / why we need it:

Deleting failed backups failed when uninstalling because failed backups will not update the backup target name in the `Status`.

Clean up system backups when deleting the default backup target. Add OwnerReferences with default backup target into system backups.

#### Special notes for your reviewer:

#### Additional documentation or context

2024-12-31 14:04 UTC, mantissahz commented
Regression test for system backup and restore:
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8109/

2024-12-31 17:09 UTC, derekbit commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
Do we use the 4th parameter (err) in updateSystemBackupRecord()?

2024-12-31 17:12 UTC, derekbit commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
If empty backupTarget remains and `State` is not `SystemBackupStateDeleting`, there will be flooding events. Right?

2025-01-01 04:55 UTC, derekbit commented on api/systembackup.go
> +			OwnerReferences: datastore.GetOwnerReferencesForBackupTarget(backupTarget),
Do we need to handle the existing system backups while upgrading Longhorn?

2025-01-02 03:55 UTC, mantissahz commented on api/systembackup.go
> +	}
Added. Thanks.

2025-01-02 03:55 UTC, mantissahz commented on controller/uninstall_controller.go
> +	if !ok || !backupTargetNameExists {
Modified. Thanks.

2025-01-02 03:59 UTC, mantissahz commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
Not sure which one you mean:
`constant.EventReasonStart`:
- it is the reason and modified to `EventReasonFailedStarting`.
`"default backup target not found"`:
- it is the error message and modified

2025-01-02 04:06 UTC, mantissahz commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
The system backup state will be changed to `longhorn.SystemBackupStateError`
and then do [cleanupLocalSystemBackupFiles](https://github.com/longhorn/longhorn-manager/blob/1875421555b48dd71782afe8e70f45bcaf6441a2/controller/system_backup_controller.go#L458-L460) at the next reconciliation. Then it won't be updated so it should not have flooding events.

2025-01-02 04:07 UTC, mantissahz commented on api/systembackup.go
> +			OwnerReferences: datastore.GetOwnerReferencesForBackupTarget(backupTarget),
Added when upgrading.

2025-01-03 02:23 UTC, derekbit commented
@mantissahz What's the status of the PR?

2025-01-03 02:26 UTC, mantissahz commented
>@mantissahz What's the status of the PR?

@derekbit it is ready for review.

2025-01-03 02:31 UTC, derekbit approved these changes
In general, LGTM.

Need to add full manual test plans include fresh installation and upgrade in the pre-check list.

cc @roger-ryao @longhorn/qa

2025-01-03 02:31 UTC, derekbit commented on upgrade/v17xto180/upgrade.go
> +
Have you tested the upgrade path and check the owner reference are patched correctly?

2025-01-03 02:35 UTC, mantissahz commented on upgrade/v17xto180/upgrade.go
> +
Yes, tested.

2025-01-03 02:38 UTC, derekbit commented on upgrade/util/util.go
> +}
Good catch!

2025-01-03 02:39 UTC, derekbit commented on upgrade/util/util.go
> +}
@mantissahz Please fix this

2025-01-03 02:39 UTC, mantissahz commented
>Need to add full manual test plans include fresh installation and upgrade in the pre-check list.
cc @roger-ryao @longhorn/qa

The pre-check list is updated with the fresh install and upgrade manual test plane in `test steps` section https://github.com/longhorn/longhorn/issues/10104#issuecomment-2566441824

2025-01-03 02:42 UTC, derekbit commented on upgrade/util/util.go
> +		sb, ok := orphans[existingSystemBackup.Name]
I assume this should be caught if you create a system backup in an older version and upgrade to v1.8.0.
Again, please remember to test the functionality first and make sure it works correctly.

2025-01-03 02:45 UTC, mantissahz commented on upgrade/util/util.go
> +}
Modified. Thanks.

2025-01-03 02:46 UTC, mantissahz commented on upgrade/util/util.go
> +		sb, ok := orphans[existingSystemBackup.Name]
Modified. Thanks.
I do tested the upgrade and it worked, I will test it again with new commit.

2025-01-03 03:01 UTC, innobead reviewed
A few feedback.

2025-01-03 03:01 UTC, innobead commented on upgrade/util/util.go
> +func updateSystemBackups(namespace string, lhClient *lhclientset.Clientset, systemBackups map[string]*longhorn.SystemBackup) error {
`orphans` is misleading. just `systemBackups`

2025-01-03 03:04 UTC, innobead commented on upgrade/util/util.go
> +		sb, ok := orphans[existingSystemBackup.Name]
For any deletion, make sure no valid backups will be deleted.

2025-01-03 08:46 UTC, mantissahz commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
Modified. If a system backup is not in final states (error, read, deleting), and the backup target is nil, it will be updated to the error state.
Thanks.

2025-01-03 08:46 UTC, mantissahz commented on controller/system_backup_controller.go
> +			constant.EventReasonStart, "default backup target not found",
Modified. Thanks

2025-01-03 08:47 UTC, mantissahz commented on api/systembackup.go
> +	backupTarget, err := s.m.GetBackupTarget(types.DefaultBackupTargetName)
Moved it to the system backup mutator. Thanks.

2025-01-03 08:48 UTC, mantissahz commented on upgrade/util/util.go
> +		if err := copier.Copy(&sbCopy, sb); err != nil {
Modified as other methods do. Thanks.

2025-01-03 08:49 UTC, mantissahz commented on upgrade/util/util.go
> +func updateSystemBackups(namespace string, lhClient *lhclientset.Clientset, systemBackups map[string]*longhorn.SystemBackup) error {
Modified. Thanks.

2025-01-06 04:34 UTC, innobead requested changes

2025-01-06 04:34 UTC, innobead commented on controller/system_backup_controller.go
> +	if backupTarget != nil {
If `backupTarget` is nil, it should just return and wait for the next reconcile instead. Otherwise, the following `c.reconcile(..)` might hit a nil exception when accessing `c.backupTargetClient` or `backupTarget`.

2025-01-06 04:34 UTC, innobead commented on controller/system_backup_controller.go
> +	SystemBackupErrBackupTarget    = "failed to get default backup target"
`SystemBackupErrDefaultBackupTargetNotFound`

2025-01-06 04:34 UTC, innobead commented on controller/system_backup_controller.go
> +		return fmt.Errorf("default backup target not found")
Can just reuse the const message, `SystemBackupErrDefaultBackupTarget`.

2025-01-06 04:34 UTC, innobead commented on controller/uninstall_controller.go
> +	_, err = c.ds.GetBackupVolumeByBackupTargetAndVolumeRO(backupTargetName, volumeName)
Any reason we can't use `backup.Status.BackupTargetName`? Is it possible that the label of backkup target is a different from the status?

2025-01-06 04:34 UTC, innobead commented on datastore/longhorn.go
> +		return nil, apierrors.NewNotFound(schema.GroupResource{Resource: "backupVolumes"}, "")
The error seems misleading. It should be an error caused by the validation error. The original error looks clearer for me. Why do we change this?

2025-01-06 04:48 UTC, mantissahz commented on controller/system_backup_controller.go
> +	if backupTarget != nil {
The default backup target will be nil (deleted before system backups are deleted ) only when uninstalling.
If we just return and wait for the next reconcile, the system backup will never clean up the finalizer when uninstalling.

>Otherwise, the following c.reconcile(..) might hit a nil exception when accessing c.backupTargetClient or backupTarget.

The system backups not in the final state (`ready`, `error`, and `deleting`) will be updated to the state `error` if the backup target is `nil` (the backup target does not exist.), and `case longhorn.SystemBackupStateReady, longhorn.SystemBackupStateError:` will not use the `c.backupTargetClient` or `backupTarget`.

2025-01-06 04:52 UTC, mantissahz commented on controller/uninstall_controller.go
> +	_, err = c.ds.GetBackupVolumeByBackupTargetAndVolumeRO(backupTargetName, volumeName)
The failed backup target will not update the `backup.Status.xxxx` so we can not use this field `backup.Status.BackupTargetName` to get the backup target name.
I will revert it and do some tests because I have modified the method `GetBackupVolumeByBackupTargetAndVolumeRO` to return the `NotFound` error if the backup target name is an empty string.

2025-01-06 06:33 UTC, mantissahz commented on controller/system_backup_controller.go
> +	SystemBackupErrBackupTarget    = "failed to get default backup target"
Modified. Thanks

2025-01-06 06:33 UTC, mantissahz commented on controller/uninstall_controller.go
> +	_, err = c.ds.GetBackupVolumeByBackupTargetAndVolumeRO(backupTargetName, volumeName)
Revert. Thanks

2025-01-06 06:35 UTC, mantissahz commented on controller/system_backup_controller.go
> +		return fmt.Errorf("default backup target not found")
Reused. Thanks.

2025-01-06 06:52 UTC, mantissahz commented on datastore/longhorn.go
> +		return nil, apierrors.NewNotFound(schema.GroupResource{Resource: "backupVolumes"}, "")
Reverted it.

>Why do we change this?

It's still an error but a `Not Found` error for the backup target or volume name is an empty string.

2025-01-06 09:13 UTC, mantissahz commented on controller/system_backup_controller.go
> +	if backupTarget == nil && !systemBackupInFinalState(systemBackup) {
I will review and refactor the codes to check if the `backupTarget` and `backupTargetClient` are nil for each state.

2025-01-06 09:14 UTC, mantissahz commented on webhook/resources/systembackup/mutator.go
> +	if len(sb.OwnerReferences) == 0 {
I assume that the `OwnerReferences` of a system backup will be created/added by Longhorn when creating the system backup resource.

2025-01-06 10:23 UTC, innobead commented on controller/system_backup_controller.go
> +	if backupTarget == nil && !systemBackupInFinalState(systemBackup) {
Yeah, we need to be careful of any potential null exception. Ideally, a static check should catch this earlier at build/compile time. I thought golangci-lint would help with this kind of issue.

2025-01-06 10:30 UTC, innobead submitted a review, later dismissed
LGTM. @derekbit and @c3y1huang might need to help with the final review before merging.

2025-01-07 01:28 UTC, derekbit commented on controller/system_backup_controller.go
> +	return sb.Status.State == longhorn.SystemBackupStateDeleting ||
nit: add a comment for explaining why we regard `SystemBackupStateDeleting` as a final state here.

2025-01-07 01:41 UTC, mantissahz commented on controller/system_backup_controller.go
> +	return sb.Status.State == longhorn.SystemBackupStateDeleting ||
Added. Thanks

2025-01-07 01:42 UTC, derekbit approved these changes
LGTM. 
Waiting for @c3y1huang's review.

2025-01-08 00:26 UTC, c3y1huang commented
> > Need to add full manual test plans include fresh installation and upgrade in the pre-check list.
> > cc @roger-ryao @longhorn/qa
> 
> The pre-check list is updated with the fresh install and upgrade manual test plane in `test steps` section [longhorn/longhorn#10104 (comment)](https://github.com/longhorn/longhorn/issues/10104#issuecomment-2566441824)

https://github.com/longhorn/longhorn/issues/10104#issuecomment-2576473428

2025-01-08 00:42 UTC, c3y1huang approved these changes

2025-01-08 01:03 UTC, merged

2025-01-08 01:10 UTC, mantissahz commented
@Mergifyio backport v1.8.x