Add func/method comments to datastore
longhorn/longhorn-manager pull request #658
Opened 2020-08-19 01:04 UTC by c3y1huang

Added comments to exported functions and methods for datastore:
* datastore.go
* kubernetes.go
* longhorn.go
* uncached.go

2020-08-19 20:00 UTC, yasker commented on datastore/kubernetes.go
> +// UpdatePersisentVolume updates the persistentvolume for the given
`PersistentVolume`. Same below.

2020-08-19 20:01 UTC, yasker commented on datastore/longhorn.go
> +// CreateSetting create longhorn setting for the given setting and namespace
`Longhorn`, same below.

2020-08-19 20:02 UTC, yasker commented on datastore/longhorn.go
> +// CreateVolume create longhorn volume resource and verifies creation
`creates a Longhorn Volume resource`.

2020-08-19 20:03 UTC, yasker commented
Add our doc writer @catherineluse

2020-08-20 01:45 UTC, c3y1huang commented on datastore/kubernetes.go
> +// DeletePersisentVolume deletes persistentvolumefor the given
done

2020-08-20 01:45 UTC, c3y1huang commented on datastore/kubernetes.go
> +// CreatePersisentVolume creates persistentvolume for the given
done

2020-08-20 01:45 UTC, c3y1huang commented on datastore/kubernetes.go
> +// UpdatePersisentVolume updates the persistentvolume for the given
done

2020-08-20 01:46 UTC, c3y1huang commented on datastore/longhorn.go
> +// CreateSetting create longhorn setting for the given setting and namespace
done

2020-08-20 01:59 UTC, c3y1huang commented on datastore/longhorn.go
> +// CreateVolume create longhorn volume resource and verifies creation
done.

2020-08-25 07:28 UTC, shuo-wu requested changes

2020-08-25 07:28 UTC, shuo-wu commented on datastore/longhorn.go
> +// UpdateInstanceManagerStatus updates Longhorn InstanceManager resource and verifies update
```
// UpdateInstanceManagerStatus updates Longhorn InstanceManager status resource and verifies update
```

2020-08-25 16:28 UTC, yasker commented on datastore/uncached.go
> +// Using cached informers should be preferred but current lister doesn't field selector.
`doesn't have a field selector`. Same below.

2020-08-27 00:42 UTC, c3y1huang commented
> LGTM, except for the commit message still contains 3 signed-off-by.

I've cleaned up the commit message. PTAL.

2020-08-27 00:55 UTC, merged