Refactor volume controller for structured log
longhorn/longhorn-manager pull request #670
Opened 2020-09-01 01:59 UTC by c3y1huang

Refactor volume controller to address structured logging implementation.

Ref:
* https://github.com/longhorn/longhorn/issues/1734
* https://github.com/longhorn/longhorn-manager/pull/661

2020-09-04 13:08 UTC, joshimoo requested changes
thanks for the commit, I added suggestions for the withFields part.

2020-09-04 13:08 UTC, joshimoo commented on controller/volume_controller.go
> +					vc.logger.Errorf("failed to parse timestamp for replica %v: %v",
Uppercase

2020-09-04 13:08 UTC, joshimoo commented on controller/volume_controller.go
> +						vc.logger.Warnf(msg)
use Warn, since you are no longer using a format string.

2020-09-04 13:08 UTC, joshimoo commented on controller/volume_controller.go
> +						vc.logger.Warnf(msg)
Also replace the message since we will be having fields for `replica` and `volume`

2020-09-04 13:08 UTC, joshimoo commented on controller/volume_controller.go
> +			vc.logger.Warnf(msg)
use Warn

2020-09-07 06:06 UTC, c3y1huang commented on controller/volume_controller.go
> +			vc.logger.Infof("Longhorn volume %v has been deleted", key)
Keeping this way since `volume` might be a nil object.

2020-09-07 06:07 UTC, c3y1huang commented
> thanks for the commit, I added suggestions for the withFields part.

Thanks for the review, I think I have addressed to all your comments. PTAL.

2020-09-09 15:48 UTC, joshimoo commented on controller/volume_controller.go
> +			vc.logger.Infof("Longhorn volume %v has been deleted", key)
How about using the name parameter together withField?
```suggestion
			vc.logger.withField("volume", name).Info("Longhorn volume has been deleted")
```

2020-09-09 16:07 UTC, joshimoo requested changes
LGTM, can be merged after the 2 comments have been addressed.

2020-09-09 16:07 UTC, joshimoo commented on controller/volume_controller.go
> +	return logger.WithField("volume", v.Name).WithField("frontend", v.Spec.Frontend)
this is good, add the following fields:
- withField("state", v.Status.State)
- withField("owner", v.Status.OwnerID)

2020-09-10 02:30 UTC, c3y1huang commented on controller/volume_controller.go
> +			vc.logger.Infof("Longhorn volume %v has been deleted", key)
XP, thanks.

2020-09-10 02:32 UTC, c3y1huang commented on controller/volume_controller.go
> +					log.WithField("replica", r.Name).WithError(err).Error("Failed to parse timestamp")
Sounds good.

2020-09-10 02:33 UTC, c3y1huang commented
> LGTM, can be merged after the 2 comments have been addressed.

Addressed to all comments. PTAL, thanks.

2020-09-10 14:36 UTC, joshimoo approved these changes
LGTM, there is one missing withErr case and some of the previously existing log messages could be improved with better grammar. I will fix the withErr case and then push, the log message grammar can be improved in the future.

2020-09-10 14:36 UTC, joshimoo commented on controller/volume_controller.go
> +	vc.logger.Warnf("Dropping Longhorn volume %v out of the queue: %v", key, err)
.WithError(err)

2020-09-10 14:38 UTC, joshimoo approved these changes

2020-09-10 15:02 UTC, joshimoo approved these changes

2020-09-10 15:03 UTC, merged