Add role/cluster binding for nfs-provisioner
longhorn/longhorn-manager pull request #671
Opened 2020-09-01 03:13 UTC by khushboo-rancher

https://github.com/longhorn/longhorn/issues/1606

I'm not sure about ```service``` ```longhorn-nfs-provisioner``` that it should be included here or not.

Signed-off-by: khushboo-rancher <60111667+khushboo-rancher@users.noreply.github.com>

2020-09-01 03:50 UTC, shuo-wu commented
The RBAC is already in `examples/rwx`. Maybe we can put the enhanced PSP in that directory if the existing PSP is editable.

2020-09-03 18:31 UTC, khushboo-rancher commented
As per my understanding, going forward to address this https://github.com/longhorn/longhorn/issues/1470, we can modify the existing podsecuritypolicy.yaml and add serviceAccount ```longhorn-nfs-provisioner```.

@joshimoo Any thoughts?

2020-09-04 13:30 UTC, joshimoo requested changes
The service account change looks good, but since we anyway give the PSP the permissions.
We might just want to only use a single service-account @yasker ?

From a security perspective it's always better to have lowest common security profiles, but we don't really do that at the moment, so it might be okay to just have a single account for now.

2020-09-04 13:30 UTC, joshimoo commented on deploy/install/01-prerequisite/02-serviceaccount.yaml
> +kind: Service
Service does not belong here.

2020-09-04 18:26 UTC, yasker commented
I am fine with using the same service account.

And the service part should be in the NFS provisioner deployment, at least before we have the HA RWX.

2020-09-04 18:27 UTC, yasker commented
Also, need to update the sign-off-by.

2020-09-04 18:45 UTC, yasker commented
Since we're merging the PSP/role binding from `examples/rwx`, we should also update the `examples/rwx` to use the Longhorn service account, etc. Otherwise, this change has no users.

2020-09-04 19:11 UTC, khushboo-rancher commented
Discussed with @yasker, we need to change the ```example/rwx``` and doc of rwx too. We can wait till the story ```HA rwx``` is delivered and then merge this to have all the relevant changes at one time.

2020-12-05 00:02 UTC, joshimoo commented
Closing this, since the changes are no longer necessary.
Once the native rwx support is merged, https://github.com/longhorn/longhorn-manager/pull/778
We can then remove the rwx provisioner example, and transition to using the native rwx support.

2020-12-05 00:02 UTC, closed without merging