Refactor uninstall controller for structured log
longhorn/longhorn-manager pull request #706
Opened 2020-10-14 07:36 UTC by c3y1huang

Refactor setting controller to address structured logging implementation.

https://github.com/longhorn/longhorn/issues/1733
https://github.com/longhorn/longhorn-manager/pull/661

2020-10-27 17:11 UTC, joshimoo requested changes
Thanks for the pr, I added some suggestions.

2020-10-27 17:11 UTC, joshimoo commented on controller/uninstall_controller.go
> +		log := c.logger.WithFields(
Add a getLoggerForInstanceManager function to the instance-manager-controller, same idea as above for the engine.
The idea is to have a getLoggerX for each crd type.

2020-10-27 17:11 UTC, joshimoo commented on controller/uninstall_controller.go
> +	log := c.logger.WithFields(
For the DaemonSet/ReplicaSet you can add the getLoggerForX functions to this controller for now.
the idea is that the fieldName is `daemonSet`, with the value of the daemonsSet name.

2020-10-27 17:11 UTC, joshimoo commented on controller/uninstall_controller.go
> +		log := c.logger.WithFields(
See above for deamonSet

2020-10-28 04:01 UTC, c3y1huang commented
> Thanks for the pr, I added some suggestions.

Thanks for the review, I've addressed all in https://github.com/longhorn/longhorn-manager/pull/706/commits/0cf8db6d12d8453bc601cdd320a27f1f4db6abaf.

2020-10-28 09:10 UTC, joshimoo approved these changes
LGTM, for the daemonset/deployment case you could have used references to the actual deployment/daemonset but since we currently only use this in the uninstall controller we can refactor that part later :)

2020-10-28 09:10 UTC, merged

2020-10-28 09:12 UTC, joshimoo commented
@c3y1huang Thanks for the PR and the addition of the new logger functions :)