Enhanced instance manager CPU reservation
longhorn/longhorn-manager pull request #828
Opened 2021-02-09 12:29 UTC by shuo-wu

longhorn/longhorn#2207

2021-02-11 18:01 UTC, joshimoo requested changes
General looks good to me, but the format and type conversions should be made much simpler.
Left some suggestions :)

2021-02-11 18:01 UTC, joshimoo commented on controller/controller_manager.go
> +			return GetCPUResourceRequirement(fmt.Sprintf("%.3f", float32(lhNode.Spec.EngineManagerCPURequest)/1000.0))
instead of throwing in a float, just pass a milli string, ParseQuantity will handle that correctly.

2021-02-12 01:00 UTC, yasker commented
I noticed that we need to use float numbers here. I am all for using an integer instead since it makes things easier. There isn't a big enough difference between 12% vs 12.5% worth our extra effort to deal with floating numbers IMO.

2021-02-22 04:58 UTC, shuo-wu commented
OK, I will update to integer instead.

2021-02-26 00:18 UTC, joshimoo approved these changes
I don't particularly like that we are always evaluating the two independent settings together, I think it should be fine to treat them independently and not limit based on the sum of both together.

That should make the validation logic simpler and allow for the mentioned use case with dedicated storage nodes.

Other than that looks good to me.
@yasker @shuo-wu what do you think about treating them independently?

2021-02-26 00:18 UTC, joshimoo commented on controller/controller_manager.go
> +		return GetCPUResourceRequirement(fmt.Sprintf("%.0fm", math.Round(float64(kubeNode.Status.Allocatable.Cpu().MilliValue())*rmCPUPercentage/100.0)))
```suggestion
		cpuRequest := lhNode.Spec.ReplicaManagerCPURequest
		if cpuRequest == 0 {
			rmCPUSetting, err := ds.GetSetting(types.SettingNameGuaranteedReplicaManagerCPU)
			if err != nil {
				return nil, err
			}
			rmCPUPercentage, err := strconv.ParseFloat(rmCPUSetting.Value, 64)
			if err != nil {
				return nil, err
			}
			cpuRequest = int(math.Round(float64(kubeNode.Status.Allocatable.Cpu().MilliValue())*rmCPUPercentage/100.0))))
		}
		return GetCPUResourceRequirement(fmt.Sprintf("%dm", cpuRequest))
```

2021-02-26 00:18 UTC, joshimoo commented on controller/controller_manager.go
> +		return GetCPUResourceRequirement(fmt.Sprintf("%.0fm", math.Round(float64(kubeNode.Status.Allocatable.Cpu().MilliValue())*rmCPUPercentage/100.0)))
Both are fine, but prefer to do the fmt in integer form.

2021-02-26 13:52 UTC, shuo-wu commented on datastore/longhorn.go
> +	guaranteedEngineManagerCPU, err := s.GetSetting(types.SettingNameGuaranteedEngineManagerCPU)
I will put this check into the `switch`.

The reason for check the sum is that:
    1. We want to guarantee that the new instance manager pods can be launched when the image is updated. Hence the sum, in theory, shouldn't be greater than 50% and we will limit it to 40% for other workload upgrade. 
    2. But at the same time we want to allow users set engine/replica manager CPU request flexibly. e.g., if some node are storage nodes, users can set replica cpu to 40% with engine cpu 0%.

2021-02-26 16:32 UTC, joshimoo approved these changes
LGTM

2021-02-26 16:34 UTC, merged