Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg
longhorn/longhorn-manager pull request #833
Opened 2021-02-24 04:44 UTC by jenting

#### Proposed Changes
- Pass labels to backup volume structure
- Add unit-test to test parseBackupVolumesList
- Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg

#### Linked Issues
https://github.com/longhorn/longhorn/issues/1539

2021-02-24 06:49 UTC, shuo-wu requested changes
1. Do not name the 2nd commit as `Refactor`
2. The unit test doesn't contain the Kubernetes status label.

2021-02-24 12:58 UTC, shuo-wu approved these changes
LGTM. Wait for the backupstore update

2021-02-26 01:59 UTC, joshimoo approved these changes
LGTM

2021-02-26 03:15 UTC, jenting commented
Bump the longhorn/backupstore version, ready to review :bow:

2021-02-26 04:08 UTC, joshimoo approved these changes

2021-02-26 04:09 UTC, merged