Retain only last copy of backup snapshot
longhorn/longhorn-manager pull request #904
Opened 2021-05-28 06:09 UTC by cclhsu

#### Proposed Changes ####

Retain only last copy of backup snapshot to resolve issue '[FEATURE] automatic successful backups should only retain the last snapshot'

#### Types of Changes ####

#### Verification ####

Test case update in https://github.com/longhorn/longhorn-tests/pull/615

#### Linked Issues ####

Refs: #2231

#### Further Comments ####

None

Signed-off-by: Clark Hsu <clark.hsu@suse.com>

2021-05-28 07:54 UTC, innobead requested changes
Just changing here is misleading, and also not really meaningful (ex: always filtered by an empty filter). 

You should make sure the old snapshots purged except the latest one after the successful backup.

2021-05-31 03:13 UTC, cclhsu commented
> Just changing here is misleading, and also not really meaningful (ex: always filtered by an empty filter).
> 
> You should make sure the old snapshots purged except the latest one after the successful backup.

Current Implementation will first get snapshots belong to recurring job and filter out the current successful snapshot for clean up.   Will need to separate the `snapshotAndCleanup` function so we do `snapshot -> backup -> cleanup backup -> cleanup snapshot`.

2021-05-31 07:12 UTC, innobead commented
Thanks, @cclhsu explanation, LGTM. 

Leaving to @PhanLe1010 to approve because he is the original code change owner then we can merge.

2021-05-31 07:12 UTC, innobead approved these changes

2021-06-01 03:55 UTC, shuo-wu reviewed
Snapshot creation and cleanup happen before backup creation. If the last snapshot is removed here, can Longhorn still do delta backup later?

2021-06-01 18:15 UTC, PhanLe1010 requested changes
Like @shuo-wu mentioned, we want to to delta backup so before finishing taking backup, we need to keep the snapshot of the last backup and the snapshot of the current running backup. 

I think we can keep everything the same and just add 1 more step to clean up the snapshots after finish taking the backup at [here](https://github.com/longhorn/longhorn-manager/blob/ec1fa07891bf1a408024f74342d115ea3de01bef/app/volume.go#L582). It means that the flow is: take a new snapshot -> clean up to keep 2 snapshot (snapshot of last backup and snapshot of the current backup) -> taking backup -> clean up snapshots to keep only 1 snapshot of the current backup. This design is resilient when in the corner case: we don't create tons of snapshots when fail to taking backup (e.g., the backup target setting is empty)

2021-06-02 21:44 UTC, PhanLe1010 approved these changes
LGTM

2021-06-04 04:01 UTC, innobead requested changes
LGTM, just minor comments to resolve.

2021-06-04 04:34 UTC, cclhsu commented on app/volume.go
> +	return job.doSnapshotCleanup(backupDone)
changed

2021-06-04 04:34 UTC, cclhsu commented on app/volume.go
> +	if err := job.doSnapshotCleanup(backupDone); err != nil {
changed

2021-06-04 04:34 UTC, cclhsu commented on app/volume.go
> +	if err := job.doSnapshotCleanup(backupDone); err != nil {
changed

2021-06-04 05:53 UTC, cclhsu commented on app/volume.go
>  	}
changed

2021-06-04 06:02 UTC, innobead approved these changes

2021-06-04 06:06 UTC, merged