Remove VA cleanup feature
longhorn/longhorn-manager pull request #911
Opened 2021-06-07 21:10 UTC by joshimoo

This removes the VA cleanup feature, since the use case is covered by the pod deletion feature.
It's better to only have a single way of accomplishing this.

I didn't touch the settings as part of this PR, since it's not important and they are just ignored.
So I can easily backport to 1.1.2

longhorn/longhorn#2060

2021-06-07 21:13 UTC, joshimoo commented
1/3 of the solution items for https://github.com/longhorn/longhorn/issues/2629

2021-06-08 13:05 UTC, joshimoo commented
Hold merge for @innobead requested review.

2021-06-08 14:04 UTC, innobead requested changes
Right now, it works as ignoring the VA deletion setting, but it seems we still need to remove/clean up related configurations like `SettingDefinitionVolumeAttachmentRecoveryPolicy` from settings, manifests and charts?

2021-06-08 15:09 UTC, joshimoo commented
@innobead I didn't want to touch the setting for 1.1.2 and I currently don't have time to look into the complexity involved of removing it.

Since we should only do it for 1.2 I created this issue to track the setting removal https://github.com/longhorn/longhorn/issues/2661

After this pr is merged the setting has now effect.

2021-06-08 17:33 UTC, innobead commented
> @innobead I didn't want to touch the setting for 1.1.2 and I currently don't have time to look into the complexity involved of removing it.
> 
> Since we should only do it for 1.2 I created this issue to track the setting removal [longhorn/longhorn#2661](https://github.com/longhorn/longhorn/issues/2661)
> 
> After this pr is merged the setting has now effect.

Sounds good to me. Let's do this way first. (but we need to update the doc at least)

2021-06-08 17:33 UTC, innobead approved these changes

2021-06-08 17:34 UTC, merged

2021-06-08 17:35 UTC, innobead commented
@joshimoo Please help backport to 1.1.2.